export const pricing = [
  {
    price: 250,
    cetagory: "Twitter",
    project: "15 Projects",
    storage: "30GB Storage",
    dataTransfer: "Unlimited data transfer",
    bandwith: "50GB Bandwith",
    security: "Enhanced security",
  },
  {
    price: 500,
    cetagory: "Facebook",
    project: "15 Projects",
    storage: "30GB Storage",
    dataTransfer: "Unlimited data transfer",
    bandwith: "50GB Bandwith",
    security: "Enhanced security",
  },
  {
    price: 800,
    cetagory: "Instagram",
    project: "15 Projects",
    storage: "30GB Storage",
    dataTransfer: "Unlimited data transfer",
    bandwith: "50GB Bandwith",
    security: "Enhanced security",
  },
  {
    price: 999,
    cetagory: "Youtube",
    project: "15 Projects",
    storage: "30GB Storage",
    dataTransfer: "Unlimited data transfer",
    bandwith: "50GB Bandwith",
    security: "Enhanced security",
  },
];
